### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by XerWandeRer** [laysionqet/timepickercompat#1]
I'va been trying to import this into my project as a module(followed this [guide](http://stackoverflow.com/questions/16588064/how-do-i-add-a-library-project-to-the-android-studio)). But having trouble as there is a dependency in library's `build.gradle` file:

``` gradle
dependencies {
    compile project(':Common')
}
```

Obviously I don't have a 'Common' directory in my project, and gradle says:

```
Error:(41) A problem occurred evaluating project ':timepickercompat'.
> Project with path ':Common' could not be found in project ':timepickercompat'.
```

Can you help me with this?

Thanks for this repository.

**Comment by laysionqet** [comment]
sorry, i have forgotten to modify the gradle file to fix the incorrect dependencies, after i extracted the module from one of my project.

Now the dependencies have been corrected
